#!/usr/bin/env bash
## 💩 Hugo's stinky step-child who won't stop putting his mark down!
# shellcheck disable=SC2164

shopt -s nullglob

pushd() { command pushd "$@" >/dev/null || exit 1; }
popd() { command popd >/dev/null || exit 1; }

err_msg() {
	echo "$1" && exit 1
}

bootstrap() {
	if [ -d "$TARGET" ]; then
		err_msg "Target bootstrap directory ($TARGET) already exists"
	fi
	echo "Bootstrapping into $TARGET"
	mkdir -p "$TARGET" || err_msg "Could not create $TARGET directory."
	pushd "$TARGET"
	mkdir posts/ && mkdir about/
	printf "# About me\n\nThis is a nice thing about me." >about/about.md
	printf "# My Blog Title\n\nThis is my blog.\n### Posts\n\n%%POSTS%%" >index.md
	printf "This is my blog header\n\n" >header.md
	printf "This is my blog footer" >footer.md
	echo "Downloading Simple CSS"
	mkdir static/
	wget --quiet -O static/style.css "https://raw.githubusercontent.com/kevquirk/simple.css/main/simple.css"
}

# Convert md file to html without extra html tags
# $1 - markdown file
# $2 - force generate if 1
md_to_html() {
	filename=${1%.md*}
	[[ "$1" -ot "$filename.html" && $2 -ne 1 ]] && return 1
	echo "Converting $(realpath "$filename.md") to HTML..."
	# TODO: handle error here and don't write if curl fails
	jq --slurp --raw-input '{"text": "\(.)", "mode": "markdown"}' <"$1" |
		curl -s --data @- https://api.github.com/markdown >"$filename.html"
}

# Convert md file to full html page
md_to_html_page() {
	filename=${1%.md*}
	unset force
	[[ "$filename.html" -ot "$HEADER" ||
		"$filename.html" -ot "$FOOTER" ]] && force=1

	md_to_html "$1" $force || return 1

	echo "...and creating HTML page $(realpath "$filename.html")..."
	printf "<!DOCTYPE html>
          <link rel=\"stylesheet\" href=\"%s\">
          <html>
          <body>
          %s
            %s
          %s
          </html>" \
		"$CSS" \
		"<header>$(<"${HEADER:-/dev/null}")</header>" \
		"$(<"$filename.html")" \
		"<footer>$(<"${FOOTER:-/dev/null}")</footer>" >"$filename.html"
}

generate_posts() {
	pushd posts/
	posts=()
	all_posts=()
	regen_index=0
	for md in *.md; do
		filename=${md%.md*}
		title=$(sed -rn 's/# (.*)/\1/p' "$md")
		timestamp=$(date -r "$md" "+%e %b %Y")
		# TODO: Add a little  if it was edited (html file already existed)
		link="**$timestamp**  [$title](/posts/$filename.html)<br>"
		[ "${#posts[@]}" -lt 6 ] && posts+=("$link")
		all_posts+=("$link")
		md_to_html_page "$md" && regen_index=1
	done
	if [[ $regen_index -eq 1 ]]; then
		echo "Regenerating posts/index.html..."
		printf "%s" "${all_posts[@]}" >index.md
		md_to_html_page index.md
		rm index.md
	fi
	popd
	return $regen_index
}

generate() {
	pushd "$TARGET"
	[ ! -d posts ] && err_msg "Posts directory not found."

	# Prepare header/footer and CSS
	md_to_html header.md
	md_to_html footer.md
	HEADER=$(realpath "./header.html")
	FOOTER=$(realpath "./footer.html")
	CSS="/static/style.css"

	if ! generate_posts; then
		echo "Regenerating index.html..."
		# Add posts section to root index.html
		sed "s;%POSTS%;### [Posts](/posts/index.html)\n${posts[*]};" index.md >index.md.tmp
		md_to_html_page index.md.tmp
		rm index.md.tmp
	fi
}

usage() {
	echo "poogo - a static-site generator for blogs."
	echo "Usage:  poogo -b [-p PATH] - bootstrap a skeleton blog"
	echo "        poogo -g [-p PATH] - generate HTML from Markdown files"
	echo "        poogo -n [-p PATH] - create new post"
}

while getopts "bghn:p:" opt; do
	case "${opt}" in
	b)
		BOOTSTRAP=1
		;;
	g)
		GENERATE=1
		;;
	n)
		NEW=${OPTARG}
		;;
	p)
		TARGET=${OPTARG}
		;;
	h | *)
		usage && exit 1
		;;
	esac
done

if [ -z "$TARGET" ]; then
	TARGET=.
fi

if [ -n "$BOOTSTRAP" ]; then
	bootstrap
	exit 0
fi

if [ -n "$NEW" ]; then
	echo "# ${NEW^}" >"$TARGET/posts/$NEW.md" ||
		err_msg "Couldn't write new post. Maybe $TARGET/posts doesn't exist?"
fi

if [ -n "$GENERATE" ]; then
	generate
fi
